qcacmn: Remove unused 'third_index' variable
Subsequent to LA.UM.8.1.r1-12800-sm8150.0 ("qcacmn: Merge tag 'LA.UM.8.1.r1-12800-sm8150.0' into neutrino-msm-hotdogb-4.14")

This silences the following compiler warning:

../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/umac/cmn_services/policy_mgr/src/wlan_policy_mgr_pcl.c:634:38: error: unused variable 'third_index' [-Werror,-Wunused-variable]
        enum policy_mgr_two_connection_mode third_index = 0;
                                            ^

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>